/* The design components present existing API state and existing action controls. */
window.MobileUI=(()=>{
 const q=s=>document.querySelector(s),n=(tag,cls,text)=>node(tag,cls,text);
 const paths={chat:'<path d="M20 11.5a8 8 0 0 1-8 8H5l-3 2v-10a9 9 0 0 1 18 0Z"/>',activity:'<path d="M4 10a8 8 0 1 1 2 8M4 4v6h6m2-4v6l4 2"/>',settings:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',device:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M1 20h22"/>',back:'<path d="m15 4-8 8 8 8"/>',search:'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',up:'<path d="M12 20V4m-6 6 6-6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',code:'<path d="m7 6-5 6 5 6m10-12 5 6-5 6m-3-15-4 18"/>'};
 paths.copy='<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h4"/>';
 paths.down='<path d="M12 4v16m-6-6 6 6 6-6"/>';
 paths.plus='<path d="M12 5v14M5 12h14"/>';
 paths.adjust='<path d="M4 7h8m4 0h4M4 17h2m4 0h10"/><circle cx="14" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>';
 paths.switch='<path d="M4 8h15m-4-4 4 4-4 4M20 16H5m4-4-4 4 4 4"/>';
 function icon(name,cls=''){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','icon '+cls);svg.setAttribute('aria-hidden','true');/* Only the fixed design icon table is markup; API content remains text. */svg.innerHTML=paths[name]||paths.settings;return svg;}
 function button(label,cls,run,ico){const b=n('button',cls);b.type='button';b.setAttribute('aria-label',label);b.onclick=run;if(ico)b.append(icon(ico));else b.textContent=label;return b;}
 function text(el,value){if(el.textContent!==String(value))el.textContent=value;}
 function setting(label,value='',ico='settings',run){const row=run?button(label,'setting',run):n('div','setting');row.replaceChildren();const mark=n('span','app-icon');mark.append(icon(ico));const name=n('span','label',label),val=n('span','value',value);row.append(mark,name,val);if(run)row.append(icon('chevron','chevron'));return {row,value:val};}
 const homes=new Map();let installed=false,page='projects',origin='projects',listSignature='',modelContext='chat';
 function move(el,target){if(!el)return;for(const [item,anchor]of homes)if(!anchor.isConnected)homes.delete(item);if(!homes.has(el)){const anchor=document.createComment('desktop position');el.before(anchor);homes.set(el,anchor);}target.append(el);}
 const root=n('section','mobile-shell');root.id='mobile-shell';document.body.append(root);
 const listPage=n('section','mobile-list-page'),toolbar=n('header','toolbar'),scroll=n('main','scroll');root.append(listPage);listPage.append(toolbar,scroll);
 const deviceButton=button('切换工作区','device-switch',()=>openDevices(),'device'),deviceLabel=n('span'),caret=n('span','','⌄');deviceButton.append(deviceLabel,caret);const deviceStatus=n('span','device-switch'),dot=n('i','dot'),statusText=n('span');deviceStatus.append(dot,statusText);
 const createButton=$('create');
 const listBack=button('返回项目','icon-button',()=>navigate('projects'),'back'),listTitle=n('strong','project-nav-title');
 const searchRow=n('div','search-row'),searchLabel=n('label','search');searchLabel.append(icon('search'));searchRow.append(searchLabel);scroll.append(searchRow);
 const clearSearch=button('清除搜索','search-clear',()=>{$('search').value='';$('search').dispatchEvent(new Event('input'));$('search').focus();});clearSearch.textContent='×';clearSearch.hidden=true;searchLabel.append(clearSearch);
 $('search').addEventListener('input',()=>{clearSearch.hidden=!$('search').value;});
 const activityConnections=n('section'),list=n('section');list.id='mobile-session-list';scroll.append(activityConnections,list);
 const nav=n('nav','bottom-nav');nav.setAttribute('aria-label','主导航');root.append(nav);const navButtons={};for(const [key,ico,label]of [['projects','chat','会话'],['activity','activity','动态'],['settings','settings','我的']]){const b=button(label,'',()=>navigate(key),ico);b.append(n('span','',label));navButtons[key]=b;nav.append(b);}const badge=n('span','badge');navButtons.activity.append(badge);
 const settings=n('main','scroll workspace-settings');root.insertBefore(settings,nav);
 const deviceCard=n('section','group device-card'),cardHeading=n('div','workspace-card-title'),cardName=n('h2'),cardSwitch=button('切换工作区','icon-button workspace-switch',()=>openDevices(),'switch'),cardStatus=n('p','workspace-status'),cardDot=n('i','dot'),cardState=n('span');cardHeading.append(cardName,cardSwitch);cardStatus.append(cardDot,cardState);deviceCard.append(n('div','device-art'),cardHeading,cardStatus);settings.append(deviceCard);
 function group(label){settings.append(n('div','group-title',label));const g=n('div','group');settings.append(g);return g;}
 const accounts=group('账户与配对');const requestsRow=setting('连接申请','','settings',()=>$('console-requests').click());accounts.append(requestsRow.row);
 const standbyRow=setting('远程待机','状态未知','activity'),controlRow=setting('远程控制','不可用','lock');deviceCard.append(standbyRow.row,controlRow.row);
 const displayGroup=group('会话');
 const notificationGroup=group('通知');notificationGroup.hidden=!cloudMode;notificationGroup.append(setting('消息通知','','settings',()=>$('notification-settings').click()).row);
 const about=group('关于');const brandRow=setting('CarryOn','','chat').row;const brandLogo=document.createElement('img');brandLogo.src=document.querySelector('.brand .mark').src;brandLogo.alt='';brandLogo.className='brand-logo';brandRow.querySelector('.app-icon').replaceChildren(brandLogo);about.append(brandRow);
 const logout=button('退出登录','logout-button',()=>{if(confirm('退出登录？设备上的 Codex 任务会继续运行。'))$('console-logout').click();});settings.append(logout);
 function sheet(id,title){const d=n('dialog');d.id=id;const head=n('div','sheet-top');head.append(n('h2','',title),button('关闭','icon-button',()=>d.close(),'close'));d.append(n('div','handle'),head);document.body.append(d);return d;}
 function pageDialog(id,title){const d=n('dialog','mobile-page-dialog');d.id=id;const head=n('header','toolbar');head.append(button('返回','icon-button',()=>d.close(),'back'),n('strong','',title),n('span','toolbar-space'));d.append(head);document.body.append(d);return d;}
 const deviceDialog=sheet('mobile-devices',''),deviceOptions=n('div','group');deviceDialog.querySelector('h2').replaceWith(button('连接新工作区？','workspace-help-link',()=>connectDialog.showModal()));deviceDialog.append(deviceOptions);
 const connectDialog=sheet('mobile-connect','连接新工作区'),connectBody=n('main','feature-page');connectDialog.classList.add('workspace-modal');
 const command=n('pre'),customCloudHint=n('p','caption','当前使用自托管服务，请使用下方 CLI 命令连接当前服务。');
 function copyBlock(content,label){
  const block=n('div','workspace-copy-block');let timer;
  const copy=button(label,'workspace-copy-button',async()=>{
   try{await navigator.clipboard.writeText(content.textContent);clearTimeout(timer);copy.replaceChildren(icon('check'));copy.setAttribute('aria-label','已复制');timer=setTimeout(()=>{copy.replaceChildren(icon('copy'));copy.setAttribute('aria-label',label);},1800);}
   catch{notice('复制失败，请长按内容复制');}
  },'copy');block.append(content,copy);return block;
 }
 connectBody.append(customCloudHint,n('h3','','桌面端'),n('p','','1. 在 CarryOn 添加工作区，选择 Codex 目录后点击「下一步」。'),n('p','','2. 选择权限及是否自动启动，点击「生成二维码」。'),n('p','','3. 用已登录的 CarryOn iOS App 扫码，核对工作区和权限后确认；也可在电脑选择已确认账号直接绑定。'),n('hr'),n('h3','','CLI'),n('p','','在已安装 CarryOn 的电脑上执行：'),copyBlock(command,'复制命令'),n('p','','按提示选择权限，用 CarryOn iOS App 扫码确认。'));connectBody.append(button('扫码或粘贴链接绑定','',()=>{connectDialog.close();window.WorkspaceBinding.open();}));connectDialog.append(connectBody);

 const detailDialog=sheet('mobile-workspace-details',''),detailBody=n('div');detailDialog.append(detailBody);
 const removeDialog=sheet('mobile-workspace-remove','移除此设备？'),removeWarning=n('p','workspace-danger'),removeConfirm=button('移除','workspace-remove-confirm',async()=>{const id=removeDialog.dataset.device;removeConfirm.disabled=true;try{const success=await removeConsoleDevice(id,true);if(success){removeDialog.close();renderDevices();}}finally{removeConfirm.disabled=false;}});removeDialog.append(removeWarning,removeConfirm,button('取消','secondary',()=>removeDialog.close()));
 async function showDeviceDetails(option){
  detailBody.replaceChildren();detailDialog.showModal();const id=option.value;detailDialog.dataset.device=id;
  const field=(label,value)=>detailBody.append(setting(label,value,'device').row);
  field('工作区',option.textContent.replace(/ · (在线|离线)$/,''));field('设备 ID',id);field('状态',option.textContent.endsWith(' · 在线')?'在线':'离线');
  if(!option.textContent.endsWith(' · 在线')){detailBody.append(n('p','','设备离线，无法读取实时主机信息。'));return;}
  const loading=n('p','','正在读取设备信息…');detailBody.append(loading);
  try{const result=await client.consoleRequest('devices/'+encodeURIComponent(id)+'/request',{method:'GET',path:'/api/status'});if(detailDialog.dataset.device!==id)return;loading.remove();const info=result.deviceInfo||{};field('主机名',info.hostname||'暂不可用');field('监听地址',info.listenHost||'暂不可用');field('监听端口',String(info.port??'暂不可用'));const standby=await client.consoleRequest('devices/'+encodeURIComponent(id)+'/request',{method:'GET',path:'/api/standby'});if(detailDialog.dataset.device!==id)return;field('远程访问',result.enabled!==true?'Codex 未连接或状态待确认':standby.effective===true?(result.remoteControl===true?'查看与操作可用，防休眠已生效':'查看可用，防休眠已生效'):standby.effective===false?'可以远程查看，休眠后可能断开':'可以远程查看，待机状态待确认');if(!result.deviceInfo)detailBody.append(n('p','','此设备版本尚未提供主机信息。'));}
  catch(e){if(detailDialog.dataset.device===id)loading.textContent='读取失败：'+e.message;}
 }

 const tools=sheet('mobile-tools','会话操作'),toolsTitle=n('p'),toolRows=n('div','group');tools.append(toolsTitle,toolRows);
 const aux=pageDialog('mobile-aux','会话信息'),auxContent=n('main','scroll feature-page');aux.append(auxContent);
 const controllerDialog=pageDialog('mobile-controller','控制会话'),controllerContent=n('main','scroll feature-page');controllerDialog.append(controllerContent);
 const model=n('div','model-popover');model.id='mobile-model';model.setAttribute('popover','auto');const modelSelect=n('select'),effortSelect=n('select');modelSelect.disabled=effortSelect.disabled=true;for(const [label,select]of [['模型',modelSelect],['思考强度',effortSelect]]){const l=n('label','',label);l.append(select);model.append(l);}model.append(n('p','caption','当前可用选项尚未同步，可在 Codex App 中调整。'));document.body.append(model);
 function openModel(context){modelContext=context;const trigger=document.activeElement;modelTrigger=trigger;const modal=[...document.querySelectorAll('dialog[open]')].at(-1);(modal||document.body).append(model);sync();model.togglePopover();if(model.matches(':popover-open')){const r=trigger.getBoundingClientRect();model.style.left=Math.max(12,Math.min(innerWidth-model.offsetWidth-12,r.right-model.offsetWidth+40))+'px';model.style.bottom=(innerHeight-r.top+12)+'px';trigger.setAttribute('aria-expanded','true');}}
 const chatScroll=n('main','scroll chat-scroll mobile-chat-scroll'),queued=n('section','queued-messages');
 const chatBack=button('返回会话','icon-button',()=>show(origin),'back'),chatTools=button('会话工具','icon-button',()=>openTools(),'more'),chatSubtitle=n('small'),running=n('div','running-label');running.append(n('span','activity-line'),n('span','','正在继续处理'));
 const jumpLatest=button('回到最新消息','mobile-jump-latest',()=>{chatScroll.scrollTo({top:chatScroll.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},'down');
 jumpLatest.hidden=true;
 const newMessageLabel=n('span','','有新消息');jumpLatest.append(newMessageLabel);
 function syncScroll(){updateLatestButton();newMessageLabel.hidden=!$('messages').dataset.newMessages;jumpLatest.dataset.unread=String(!newMessageLabel.hidden);jumpLatest.setAttribute('aria-label',$('messages').dataset.newMessages?'有新消息，回到最新':'回到最新消息');jumpLatest.title=jumpLatest.getAttribute('aria-label');jumpLatest.hidden=!installed||page!=='chat'||chatScroll.scrollHeight-chatScroll.scrollTop-chatScroll.clientHeight<160;jumpLatest.style.bottom=($('composer').offsetHeight+12)+'px';}
 chatScroll.addEventListener('scroll',syncScroll,{passive:true});
 const chatResize=new ResizeObserver(syncScroll);chatResize.observe(chatScroll);chatResize.observe($('messages'));chatResize.observe($('composer'));
 const mainInput=n('div','input-shell'),mainActions=n('div','composer-actions'),modelButton=button('查看当前模型与思考强度','model-button',()=>openModel('chat'),'adjust');mainActions.append(modelButton);
 function sendIcon(b,label){if(b.childNodes.length===1&&b.firstElementChild?.classList.contains('send'))return;b.setAttribute('aria-label',label);const mark=n('span','send');mark.append(icon('up'));b.replaceChildren(mark);}
 function composer(input,submit,context){const form=n('div','composer production-composer'),shell=n('div','input-shell'),actions=n('div','composer-actions');form.append(shell);const attach=button('添加图片','icon-button',()=>{},'plus');attach.disabled=true;attach.title='当前操作仅支持文字';shell.append(attach);input.rows=1;input.setAttribute('aria-label',context==='new'?'描述你希望完成的任务':'修改这条指令');input.placeholder=context==='new'?'描述你希望完成的任务…':'修改这条指令…';if(context==='edit')shell.append(input);else move(input,shell);actions.append(button('模型与思考强度','model-button',()=>openModel(context),'adjust'));if(context==='edit')actions.append(submit);else move(submit,actions);submit.classList.add('send-touch');sendIcon(submit,context==='new'?'创建会话':'替换并重新执行');shell.append(actions);return form;}
 const newBody=n('main','scroll feature-page'),newProjectGroup=n('div','group');newBody.append(n('p','caption','项目'),newProjectGroup);
 function renderDevices(){
  deviceOptions.replaceChildren(...[...$('console-device').options].map(o=>{
   const wrap=n('div','workspace-swipe'),actions=n('div','workspace-row-actions');
   const remove=button('移除','destructive',()=>{removeDialog.dataset.device=o.value;removeWarning.textContent='移除「'+o.textContent.replace(/ · (在线|离线)$/,'')+'」后将撤销连接凭证，重新接入需在电脑端再次申请。已被 Codex 接收的任务可能仍在执行。';removeDialog.showModal();});
   actions.append(remove,button('详情','',()=>showDeviceDetails(o)));wrap.append(actions);
   let suppressClick=false;
   const row=button(o.textContent,'workspace-option',()=>{if(suppressClick){suppressClick=false;return;}if(wrap.classList.contains('revealed')){wrap.classList.remove('revealed');return;}if(o.value!==$('console-device').value){$('console-device').value=o.value;$('console-device').dispatchEvent(new Event('change'));}deviceDialog.close();});row.replaceChildren();
   const mark=n('span','app-icon');mark.append(icon('device'));const body=n('span','workspace-option-text');body.append(n('strong','',o.textContent.replace(/ · (在线|离线)$/,'')),n('small',o.selected?'workspace-current':'',o.selected?'当前使用':o.textContent.endsWith(' · 在线')?'在线':'离线'));row.append(mark,body);row.setAttribute('aria-pressed',String(o.selected));wrap.append(row);
   let start;
   row.addEventListener('pointerdown',e=>{if(e.isPrimary&&e.button===0){suppressClick=false;start={x:e.clientX,y:e.clientY};}});
   row.addEventListener('pointermove',e=>{if(start&&Math.abs(e.clientX-start.x)>12&&Math.abs(e.clientX-start.x)>Math.abs(e.clientY-start.y))row.setPointerCapture(e.pointerId);});
   row.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){wrap.classList.toggle('revealed',dx<0);suppressClick=true;}start=null;});
   row.addEventListener('pointercancel',()=>{start=null;});
   row.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();wrap.classList.toggle('revealed',e.key==='ArrowLeft');}});

   return wrap;
  }));if(!deviceOptions.childNodes.length)deviceOptions.append(n('p','','暂无工作区'));
 }
 function openDevices(){renderDevices();deviceDialog.showModal();}

 let auxKind='';
 function restoreAux(){for(const child of [...auxContent.children]){const anchor=homes.get(child);if(anchor?.isConnected){anchor.before(child);anchor.remove();homes.delete(child);}}}
 function openAux(title,el){tools.close();restoreAux();auxKind=el===$('conversation-info')?'info':el.classList.contains('jobs-panel')?'jobs':el.classList.contains('mobile-queue')?'queue':'settings';aux.firstChild.querySelector('strong').textContent=title;move(el,auxContent);if(el.tagName==='DETAILS')el.open=true;aux.showModal();}

 aux.addEventListener('close',restoreAux);
 function openTools(){restoreAux();text(toolsTitle,$('title').textContent);toolRows.replaceChildren();const operations=$('operations');for(const item of operations.children){const label=item.tagName==='DETAILS'?item.querySelector('summary')?.textContent:item.textContent;if(label==='排队任务')toolRows.append(setting('队列管理','','settings',()=>openAux('队列管理',item)).row);if(label==='会话设置')toolRows.append(setting('高级会话设置','','settings',()=>openAux('高级会话设置',item)).row);}for(const [label,run]of [['子会话',()=>{tools.close();$('open-subagents').click();}],['临时聊天',()=>{tools.close();$('open-side').click();}],['查看改动',()=>{tools.close();$('view-changes').click();}],['会话信息',()=>openAux('会话信息',$('conversation-info'))],['请求记录',()=>openAux('请求记录',q('.jobs-panel'))]])toolRows.append(setting(label,'','settings',run).row);tools.showModal();}


 const storage=n('div');storage.id='mobile-storage';storage.hidden=true;document.body.append(storage);
 let originalCreateHead,loginHead,originalPlaceholder,desktopText;
 const presentationIds=['create','close-dialog','attach-images','auth-description','pair'];
 let modelTrigger=null;model.addEventListener('toggle',()=>modelTrigger?.setAttribute('aria-expanded',String(model.matches(':popover-open'))));
 function layout(){root.hidden=!mobileLayout.matches;chatBack.hidden=chatTools.hidden=!mobileLayout.matches;
  if(mobileLayout.matches&&!installed){desktopText=presentationIds.map(id=>[id,$(id).textContent,$(id).className]);installed=true;document.body.classList.add('mobile-ready');
   move(q('main>aside'),storage);move(q('.conversation'),root);root.insertBefore(q('.conversation'),nav);move($('search'),searchLabel);searchLabel.append(clearSearch);move($('more'),scroll);move($('project-filter-label'),searchRow);move($('clear-read'),scroll);move($('inactive-preference'),displayGroup);
   move(q('.controller-box'),controllerContent);q('.controller-box').open=true;
   move(q('.conversation>.timeline-toolbar'),storage);move(q('.jobs-panel'),storage);
   const head=q('.conversation-head');head.classList.add('toolbar','chat-header');head.prepend(chatBack);head.append(chatTools);head.firstElementChild.nextElementSibling.classList.add('chat-heading');move($('cwd'),storage);head.querySelector('.chat-heading').append(chatSubtitle);move($('history-source'),head.querySelector('.chat-heading'));
   const messages=$('messages');messages.before(chatScroll);move(messages,chatScroll);move($('requests'),chatScroll);chatScroll.append(queued,running);q('.conversation').append(jumpLatest);
   const form=$('composer');form.append(mainInput);move($('attach-images'),mainInput);move($('prompt'),mainInput);mainInput.append(mainActions);move($('send'),mainActions);$('send').classList.add('send-touch');$('attach-images').classList.add('icon-button');$('attach-images').replaceChildren(icon('plus'));$('prompt').rows=1;originalPlaceholder=$('prompt').placeholder;$('prompt').placeholder='回复 CarryOn…';
   move($('image-previews'),form);form.prepend($('image-previews'));move(form.querySelector('.composer-footer'),storage);
   move($('pairing'),root);loginHead=n('header','toolbar login-toolbar');loginHead.append(n('strong','','CarryOn'));$('pairing').prepend(loginHead);q('.auth-symbol').classList.add('login-symbol');q('.auth-card').classList.add('feature-page');text($('auth-description'),'查看进展，继续对话。\n换个设备，接着做。');text($('pair'),'登录');$('token').placeholder='';if(cloudMode)q('label[for=token]').textContent='密码';
   originalCreateHead=q('#create-form .dialog-head');originalCreateHead.classList.add('toolbar');move($('close-dialog'),originalCreateHead);originalCreateHead.prepend($('close-dialog'));$('close-dialog').replaceChildren(icon('back'));originalCreateHead.append(n('span','toolbar-space'));move($('new-project-label'),newProjectGroup);$('create-form').append(newBody,composer($('new-prompt'),$('submit-create'),'new'));$('create-dialog').classList.add('mobile-page-dialog');
   const requestsDialog=$('requests-dialog');requestsDialog.classList.add('mobile-page-dialog');const requestHead=n('header','toolbar request-toolbar');requestHead.append(button('返回','icon-button',()=>requestsDialog.close(),'back'),n('strong','','连接申请'),n('span','toolbar-space'));requestsDialog.prepend(requestHead);const requestBody=n('main','scroll feature-page mobile-request-body');requestsDialog.append(requestBody);move($('connection-requests'),requestBody);
   const notification=$('notification-dialog');notification.classList.add('mobile-page-dialog');const nh=n('header','toolbar notification-toolbar');nh.append(button('返回','icon-button',()=>notification.close(),'back'),n('strong','','消息通知'),n('span','toolbar-space'));notification.prepend(nh);
   show(selected?'chat':page);
  }else if(!mobileLayout.matches&&installed){installed=false;for(const [el,anchor]of homes){if(anchor.isConnected){anchor.before(el);anchor.remove();}}homes.clear();document.body.classList.remove('mobile-ready');q('.conversation').hidden=false;$('create').hidden=false;delete document.body.dataset.mobilePage;for(const d of [tools,aux,deviceDialog,connectDialog,controllerDialog])d.close();document.querySelectorAll('[data-mobile-inline]').forEach(el=>el.remove());$('history-source').hidden=false;chatScroll.remove();chatSubtitle.remove();mainInput.remove();root.querySelectorAll('.production-composer').forEach(el=>el.remove());$('create-form').querySelectorAll('.production-composer').forEach(el=>el.remove());newBody.remove();loginHead?.remove();q('.notification-toolbar')?.remove();q('.request-toolbar')?.remove();q('.mobile-request-body')?.remove();$('requests-dialog').classList.remove('mobile-page-dialog');$('create-dialog').classList.remove('mobile-page-dialog');$('notification-dialog').classList.remove('mobile-page-dialog');q('.controller-box').open=false;$('create').disabled=!canWrite();$('prompt').placeholder=originalPlaceholder;$('prompt').style.height='';$('send').classList.remove('send-touch');$('send').removeAttribute('aria-label');updateComposeButton();for(const [id,value,cls]of desktopText){$(id).textContent=value;$(id).className=cls;}originalCreateHead.classList.remove('toolbar');originalCreateHead.querySelectorAll('.toolbar-space').forEach(el=>el.remove());}
  sync();
 }
 let listPosition=0;
 function show(next){if(next==='chat'&&page!=='chat')listPosition=list.scrollTop;if(next!=='chat'&&page==='chat'){navigationVersion++;activityNavigationThread=null;requestAnimationFrame(()=>{list.scrollTop=listPosition;});}if(next==='chat'&&page!=='chat')origin=page==='settings'?'projects':page;page=next;if(installed)document.body.dataset.mobilePage=next;sync();}
 function navigate(next){const repeat=next==='projects'&&page==='projects';show(next);if(next==='projects')(repeat&&workspaceView==='projects'?$('show-all'):$('show-projects')).click();if(next==='activity')$('show-activity').click();if(next==='settings'&&enabled)refreshStandby();}
 let standbyScope='';async function refreshStandby(){const scope=draftScope();standbyScope=scope;try{const result=await api('/standby');if(scope!==draftScope())return;text(standbyRow.value,result.error?'状态异常':result.effective===true?'防休眠已生效':result.enabled===true?'已开启，尚未生效':result.effective===false?'未生效，休眠后可能断开':'状态未知');}catch{if(scope===draftScope())text(standbyRow.value,'状态未知');}}
 function dateLabel(t){const value=t.updated_at||t.updatedAt;if(!value)return '';const date=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(date.getTime())?'':date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}
 function stateOf(t){return threadStatuses[t.id]||t.status||{state:'unknown',label:'状态未知'};}
 function row(t){const state=stateOf(t),wait=state.state==='waiting',live=state.state==='running';const b=button(t.title||'未命名会话','session',()=>selectThread(t.id));b.textContent='';b.dataset.thread=t.id;if(workspaceView==='activity'&&t.activityRead)b.style.opacity='.65';const mark=n('span','app-icon '+(wait?'wait':live?'live':state.state==='failed'?'failed':''));mark.append(icon(wait?'lock':live?'code':'chat'));const body=n('span','session-body'),meta=n('span','session-meta');meta.append(n('span','',t.cwd?.split('/').filter(Boolean).at(-1)||'独立会话'),n('span','',dateLabel(t)));const title=n('strong','session-title',t.title||'未命名会话');if(t.unread){const dot=n('i','unread-dot');dot.setAttribute('aria-label','有未读消息');title.append(dot);}body.append(meta,title);if(t.preview)body.append(n('span','session-preview',t.preview));if(state.state!=='idle'){const label=n('span','session-state '+(wait?'wait':state.state==='failed'?'failed':''));label.append(n('i','dot'),n('span','',live?'进行中':wait?'等待确认':state.label||'状态未知'));body.append(label);}b.append(mark,body,icon('chevron','chevron'));return b;}
 function renderList(){const position=list.scrollTop;renderListContent();if(!listPage.hidden)list.scrollTop=position;}
 function renderListContent(){const signature=JSON.stringify([workspaceView,workspaceProject,workspaceProjects,threads,threadStatuses,enabled,client.device,listLoadState]);if(listSignature===signature)return;listSignature=signature;list.replaceChildren();
  if(!enabled){list.append(viewState(cloudMode&&!client.device?'请先选择工作区':'工作区暂未连接',{symbol:'offline'}));return;}
  const hasRows=(workspaceView==='projects'?workspaceProjects:threads).length>0;
  if(listLoadState.phase==='initial'){list.append(viewState('正在加载…',{loading:true}));return;}
  if(listLoadState.error){
    const failure=viewState(hasRows?'刷新失败':'加载失败',{detail:listLoadState.error,symbol:'offline',retry:()=>loadThreads()});
    if(hasRows)failure.classList.add('compact');list.append(failure);if(!hasRows)return;
  }
  if(listLoadState.phase==='refresh'){const refreshing=viewState('正在刷新…',{loading:true});refreshing.classList.add('compact');list.append(refreshing);}

  if(workspaceView==='projects'){const group=n('div','group');for(const project of workspaceProjects){const b=button(project.name,'project-row',()=>{workspaceView='threads';workspaceProject=project.id;$('search').value='';$('project-filter').value='all';loadThreads().catch(e=>notice(e.message));});b.textContent='';const folder=n('span','project-folder');folder.append(icon('code'));const body=n('span','project-body');body.append(n('strong','',project.name),n('span','project-count',project.total+' 个会话'));const counts=n('span','project-statuses');for(const [key,label,cls]of [['waiting','待处理','project-wait'],['running','进行中','project-running'],['unread','未读','project-unread'],['unknown','状态未知','']])if(project[key])counts.append(n('span',cls,project[key]+' '+label));if(!counts.childNodes.length)counts.append(n('span','','暂无进行中的任务'));body.append(counts);b.append(folder,body,icon('chevron','chevron'));group.append(b);}list.append(group);if(!workspaceProjects.length)list.append(viewState($('search').value?'没有搜索结果':'暂无项目',{symbol:$('search').value?'search':'folder'}));return;}
  const groups=workspaceView==='activity'?[['动态',()=>true]]:[['待处理',t=>t.actionable||['waiting','failed'].includes(stateOf(t).state)],['进行中',t=>stateOf(t).state==='running'],['最近',t=>!t.actionable&&stateOf(t).state==='idle'],['状态待确认',t=>!['waiting','failed','running','idle'].includes(stateOf(t).state)]];
  for(const [label,match]of groups){const items=threads.filter(match);if(!items.length)continue;const heading=n('div','group-title',label);heading.append(n('span','',items.length));const group=n('div','group');group.append(...items.map(row));list.append(heading,group);}if(!threads.length)list.append(viewState($('search').value?'没有搜索结果':workspaceView==='activity'?'暂无动态':'暂无会话',{symbol:$('search').value?'search':'chat'}));
 }
 function decorate(){if(!installed)return;if(aux.open&&['settings','queue'].includes(auxKind)){const selector=auxKind==='queue'?'.mobile-queue':'.mobile-session-settings',current=$('operations').querySelector(selector)||auxContent.querySelector(selector);if(current){if(current.parentNode!==auxContent)move(current,auxContent);current.open=true;}else aux.close();}const requests=$('requests');if(requests.parentNode!==chatScroll)chatScroll.insertBefore(requests,running);for(const card of requests.querySelectorAll('.request-card')){
   card.classList.add('approval');
   if(card.dataset.action==='user-input'&&!card.querySelector('[data-mobile-inline]')){
    const input=[...card.querySelectorAll('textarea')].at(-1),submit=[...card.querySelectorAll('button')].find(b=>b.textContent==='提交回答');
    if(input&&submit){const label=input.closest('label'),form=n('div','composer inline-composer'),shell=n('div','input-shell'),actions=n('div','composer-actions');form.dataset.mobileInline='true';label.after(form);input.setAttribute('aria-label',label.firstChild?.textContent||'输入你的回答');input.placeholder='输入你的回答…';input.rows=1;move(input,shell);move(submit,actions);submit.classList.add('send-touch');sendIcon(submit,'提交回答');shell.append(actions);form.append(shell);}
   }
  }}
 function sync(){if(!installed)return;$('history-source').hidden=['','已同步原生记录'].includes($('history-source').textContent);updateCreateButton();if(cloudMode){text(command,client.initializationCommand||'本地 HTTP 服务仅供协议测试，绑定请使用 HTTPS 服务。');customCloudHint.hidden=client.initializationCommand==='carryon init';}const queue=composeHistory?.queue?.messages||[];queued.hidden=!queue.length;const queueSignature=JSON.stringify(queue);if(queued.dataset.signature!==queueSignature){queued.dataset.signature=queueSignature;queued.replaceChildren(n('span','','等待当前请求处理后继续 · '+queue.length+' 条'),...queue.map(item=>n('p','',item.text||'')));}
  const logged=$('pairing').hidden;listPage.hidden=!logged||!['projects','activity'].includes(page);settings.hidden=!logged||page!=='settings';q('.conversation').hidden=!logged||page!=='chat';nav.hidden=!logged||page==='chat';
  const active=page==='chat'?origin:page;for(const [key,b]of Object.entries(navButtons)){b.classList.toggle('active',key===active);if(key===active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}
  const requestCount=cloudMode?Number($('console-requests').textContent.split('·')[1]||0):0,activityCount=Number($('show-activity').textContent.split('·')[1]||0);text(badge,requestCount+activityCount);badge.hidden=!(requestCount+activityCount);text(requestsRow.value,requestCount);requestsRow.value.classList.add('request-count-badge');requestsRow.value.hidden=!requestCount;requestsRow.value.setAttribute('aria-label',requestCount+' 项待确认');
  const option=$('console-device').selectedOptions[0],name=cloudMode?(option?.textContent.replace(/ · (在线|离线)$/,'')||'工作区'):'本机工作区',online=cloudMode?option?.textContent.endsWith(' · 在线'):enabled,state=cloudMode&&!option?'未选择工作区':!online?'离线':enabled?(streamReady?'在线':'连接待恢复'):'状态异常';text(deviceLabel,name);text(cardName,name);text(statusText,state);text(cardState,state);dot.dataset.state=cardDot.dataset.state=state;cardSwitch.hidden=!cloudMode;deviceButton.disabled=!cloudMode;
  text(controlRow.value,!streamReady?'连接待恢复':canWrite()?'已允许':enabled?'只读':'不可用');accounts.hidden=!cloudMode;accounts.previousElementSibling.hidden=!cloudMode;logout.hidden=!cloudMode;
  const project=workspaceProjects.find(p=>p.id===workspaceProject),projectView=workspaceView==='threads';if(toolbar.dataset.view!==workspaceView){toolbar.dataset.view=workspaceView;toolbar.replaceChildren(...(projectView?[listBack,listTitle]:[deviceButton,deviceStatus]));move(createButton,projectView?toolbar:searchRow);}text(listTitle,project?.name||'项目会话');searchRow.hidden=false;$('create').hidden=workspaceView==='activity';$('create').classList.add('icon-button');$('create').textContent='＋';$('create').setAttribute('aria-label','新建会话');$('create').disabled=!canWrite();$('search').placeholder=workspaceView==='projects'?'搜索项目':'搜索会话';clearSearch.hidden=!$('search').value;
  activityConnections.hidden=workspaceView!=='activity'||!requestCount;const requestSignature=String(requestCount);if(activityConnections.dataset.count!==requestSignature){activityConnections.dataset.count=requestSignature;activityConnections.replaceChildren();const h=n('div','group-title','连接申请');h.append(n('span','',requestCount+' 项'));const g=n('div','group');g.append(setting('有新的电脑申请连接',requestCount+' 项待确认','settings',()=>$('console-requests').click()).row);activityConnections.append(h,g);}
  text(chatSubtitle,($('cwd').textContent.split('/').filter(Boolean).at(-1)||'会话')+' · '+state+($('runtime').textContent.match(/已执行 [^·]+/)?.[0]?' · '+$('runtime').textContent.match(/已执行 [^·]+/)[0].trim():''));
  const modelName=modelContext==='new'?'会话默认':composeHistory?.controls?.settings?.model||composeHistory?.metadata?.latestModel||'会话默认',effort=modelContext==='new'?'会话默认':composeHistory?.controls?.settings?.effort||composeHistory?.metadata?.latestReasoningEffort||'会话默认';if(modelSelect.options[0]?.text!==modelName)modelSelect.replaceChildren(new Option(modelName));if(effortSelect.options[0]?.text!==effort)effortSelect.replaceChildren(new Option(effort));
  const send=$('send');const label=send.textContent.includes('停止任务')?'停止任务':send.textContent.includes('发送任务')?'发送指令':send.getAttribute('aria-label')||'发送指令';sendIcon(send,label);send.dataset.mode=label==='停止任务'?'stop':'send';send.firstElementChild.classList.toggle('stop',label==='停止任务');running.hidden=composeHistory?.runtime?.type!=='active'||composeHistory?.syncing===true||!composeHistory?.timeline?.length;modelButton.disabled=!selected;$('prompt').placeholder='回复 CarryOn…';
  renderList();decorate();syncScroll();
 }
 $('new-prompt').addEventListener('input',sync);
 const observer=new MutationObserver(sync);observer.observe($('operations'),{attributes:true,subtree:true,attributeFilter:['disabled']});for(const el of [$('pairing'),$('status'),$('runtime'),$('console-device'),$('console-requests'),$('send'),$('controller')])observer.observe(el,{childList:true,subtree:true,attributes:el===$('pairing'),attributeFilter:el===$('pairing')?['hidden']:undefined});
 $('prompt').addEventListener('input',()=>{if(installed){$('prompt').style.height='auto';$('prompt').style.height=Math.min($('prompt').scrollHeight,100)+'px';}});
 scroll.addEventListener('touchstart',event=>{scroll.startY=list.scrollTop===0&&event.touches.length===1?event.touches[0].clientY:null;},{passive:true});scroll.addEventListener('touchend',event=>{if(scroll.startY!==null&&event.changedTouches[0]?.clientY-scroll.startY>80&&enabled&&listLoadState.phase==='idle')loadThreads().catch(e=>notice(e.message));scroll.startY=null;},{passive:true});scroll.addEventListener('touchcancel',()=>{scroll.startY=null;},{passive:true});
 mobileLayout.addEventListener('change',layout);layout();return {sync,show,decorate,beforeOperationsRender:restoreAux,resetOperations(){restoreAux();aux.close();}};
})();
