/* UI-only models. No network requests, credentials or real device operations. */
let loggedIn=false,controller='准备下一次发布',pairExpires=0,pairCode='',extraLoaded=false;
let queue=[],nextQueue=1;
let questionDraft='';
let attachments=[],requestType='command',answered=new Set(),confirmation=null;
const sessionSettings={model:'',effort:'',advanced:'{}'};
const records=[{title:'历史请求',state:'结果待确认',detail:'设备连接中断。请在 Codex App 核对；不会自动重发。'}];
const writeDisabled=()=>mode==='control'?'':'disabled';
function featureRow(id,label,value=''){return `<button class="setting" data-feature="${id}"><span class="app-icon">${icon(id==='logout'?'back':id==='pairing'?'lock':'settings')}</span><span class="label ${id==='logout'?'destructive':''}">${label}</span><span class="value">${value}</span>${icon('chevron','chevron')}</button>`}
function page(title,body,back='devices'){app.innerHTML=`<header class="toolbar"><button class="icon-button" data-route="${back}" aria-label="返回">${icon('back')}</button><strong>${title}</strong><span style="width:44px"></span></header><main class="scroll feature-page">${body}</main>`}
function field(name,label,value='',kind='text'){return `<label class="form-field">${label}${kind==='textarea'?`<textarea name="${name}" required>${esc(value)}</textarea>`:`<input name="${name}" type="${kind}" value="${esc(value)}" required autocomplete="off">`}</label>`}
function form(id,body,label){return `<form id="${id}"><fieldset ${writeDisabled()}>${body}<p class="form-error" role="alert"></p><button class="primary">${label}</button></fieldset></form>${mode!=='control'?'<p class="read-only-note">当前为只读或离线，无法提交操作。</p>':''}`}
function record(title,detail='本地演示已完成；未向真实设备发送请求。'){records.unshift({title,state:'演示完成',detail})}
function confirmAction(title,detail,run){confirmation=run;sheet.innerHTML=`<div class="handle"></div><div class="sheet-top"><h2 id="sheet-title">${title}</h2><button class="icon-button" data-action="close" aria-label="关闭">${icon('close')}</button></div><p>${esc(detail)}</p><button class="primary" data-feature="commit-confirm">确认</button><button class="secondary" data-action="close">取消</button>`;if(!sheet.open)sheet.showModal()}
function showFeature(name){if(name==='operations'){const t=sessions.find(s=>s.id===current);sheet.innerHTML=`<div class="handle"></div><div class="sheet-top"><h2 id="sheet-title">会话操作</h2><button class="icon-button" data-action="close" aria-label="关闭">${icon('close')}</button></div><p>${esc(t.title)}</p><div class="group">${(t.state==='done'?[['compact','压缩上下文'],['edit','编辑最后一轮']]:[]).map(([id,l])=>featureRow(id,l)).join('')}${[['advanced-settings','高级会话设置'],['temporary','临时聊天'],['metadata','会话信息'],['records','请求记录']].map(([id,l])=>featureRow(id,l)).join('')}</div>`;sheet.showModal();return}if(sheet.open)sheet.close();location.hash=name}
function login(){page('ConnectNow',`<div class="login-hero"><div class="login-symbol">↗</div><p>查看进展，继续对话。<br>让工作随你同行。</p></div><form id="login-form">${field('token','控制台登录凭证','','password')}<p class="form-error" role="alert"></p><button class="primary">登录</button></form><p class="caption">登录后选择已登记的电脑。登录凭证与设备配对码用途不同。</p><div class="auth-note">交互原型：输入 demo 即可体验。请勿输入真实凭证。</div>`, 'login');document.querySelector('[data-route="login"]').hidden=true}
function renderFeature(route){if(!loggedIn){login();return true}if(route==='login'){location.hash='tasks';return true}if(route==='notifications'){renderNotifications();return true}if(route==='bind-workspace'){renderWorkspaceBinding();return true}if(route==='link'){renderConnectionRequests();return true}if(workspaceId!=='macbook'&&!['devices','pairing','link','inbox'].includes(route)){page('工作区',`<div class="empty">${esc(activeWorkspace().name)} · ${workspaceStatus().text}<br><small>连接恢复后可查看此工作区的会话。</small></div>`,'devices');return true}const back='chat/'+current;
 if(route==='pairing'){page('备用配对码',`<p class="caption">在${esc(activeWorkspace().name)}上连接此控制台。配对码仅能使用一次，5 分钟内有效。</p><div class="code-display" id="pair-code">${pairCode||'尚未生成'}</div><p class="code-caption" id="pair-timer"></p><button class="primary" data-feature="generate-pair">${pairCode?'重新生成':'获取配对码'}</button><button class="load-more" data-feature="copy-pair" ${pairCode?'':'disabled'}>复制配对码</button><div class="group-title">在电脑上完成连接</div><ol class="caption"><li>打开本机 ConnectNow。</li><li>进入云端接入，填写控制台地址。</li><li>输入配对码，在本机决定是否允许远程控制。</li></ol><pre>connectnow start\nconnectnow cloud pair --url https://console.example.com</pre><p class="auth-note">示例地址与配对码仅用于界面预览，不可用于实际连接。</p>`);updateTimer();return true}

 if(route==='new'){page('新建会话',`<p class="caption">通过专用控制会话创建独立任务。</p><div class="group">${featureRow('controller','控制会话',controller||'尚未设置')}</div>`,'tasks');app.insertAdjacentHTML('beforeend',conversationComposer('new'));updateComposer();return true}
 if(route==='controller'){page('新建会话设置',form('controller-form',`<p class="caption">在电脑上的 Codex App 中打开专用、空闲的控制会话。只有满足原生创建能力的会话可用。</p><label class="form-field">控制会话<select name="controller"><option value="">暂不设置</option><option ${controller?'selected':''}>准备下一次发布</option></select></label>`,'保存设置'),'tasks');return true}
 if(route==='edit'){page('编辑最后一轮','<p class="caption">替换最后一轮输入及后续结果，并重新执行。</p>',back);app.insertAdjacentHTML('beforeend',conversationComposer('edit'));updateComposer();return true}
 if(route==='advanced-settings'){page('高级会话设置',form('settings-form',`<p class="caption">按现有契约修改 model、effort、serviceTier、cwd、approvalPolicy、approvalsReviewer、sandboxPolicy、permissions、activePermissionProfile、collaborationMode、personality、summary、multiAgentMode。权限等变更影响后续任务。</p>${field('advanced','设置 JSON',sessionSettings.advanced,'textarea')}`,'保存设置'),back);return true}
 if(route==='temporary'){page('临时聊天',`<label class="form-field">选择临时聊天<select id="temporary-select"><option>方案讨论 · 只读</option><option>边界检查 · 只读</option></select></label><div class="group" style="padding:20px"><p class="response" id="temporary-message">可以先核对核心流程，再逐项检查操作边界。</p></div><p class="caption">仅同步已存在的临时聊天。发送或新建请在 Codex App 中操作。</p><details class="tool"><summary>临时聊天信息</summary><pre>来源：已关联临时聊天\n同步状态：已加载（演示）</pre></details>`,back);return true}
 if(route==='metadata'){page('会话信息',`<div class="group">${setting('chat','项目',sessions.find(s=>s.id===current).project)}${setting('device','设备','我的 MacBook')}${setting('activity','状态',sessions.find(s=>s.id===current).state)}</div><pre>历史来源：原生会话投影\n工作目录：对应项目工作空间\n模型：${esc(sessionSettings.model||'会话默认')}\n思考强度：${esc(sessionSettings.effort||'默认')}</pre><p class="caption">当前展示演示信息。正式页面应读取原生元数据。</p>`,back);return true}
 if(route==='records'){page('请求记录',`<div class="group">${records.map(r=>`<div class="request-record"><strong>${esc(r.title)}</strong><small>${esc(r.state)}</small><p>${esc(r.detail)}</p></div>`).join('')}</div><p class="caption">结果待确认时请核对原生 App，不自动重发任务。</p>`,back);return true}
 return false}
function requestBody(requestType){let body='';if(answered.has(requestType)){body='<div class="group empty">此演示请求已处理</div>'}else if(['command','file'].includes(requestType)){body=`<div class="approval-actions"><button class="primary" data-decision="once" ${writeDisabled()}>仅本次允许</button><button class="secondary" data-decision="decline" ${writeDisabled()}>拒绝</button></div><details class="approval-more"><summary>更多选项</summary><div class="group">${[['session','在此会话中允许'],['cancel','取消并中断']].map(([a,l])=>`<button class="setting" data-decision="${a}" ${writeDisabled()}><span class="label">${l}</span>${icon('chevron','chevron')}</button>`).join('')}</div></details><p class="approval-example">此处仅为审批示例，实际选项以当前请求为准。</p>`}else if(requestType==='permissions'){body=form('permission-form',`<label class="form-field">授权有效期<select name="scope"><option value="turn">仅本轮</option><option value="session">整个会话</option></select></label>${field('permissions','授予权限 JSON','{}','textarea')}<label class="check-field"><input type="checkbox" name="review" checked>继续逐条审查本轮命令</label>`,'授予所选权限')+`<button class="load-more" data-decision="decline" ${writeDisabled()}>拒绝</button>`}else if(requestType==='question'){body=`<p>这次优先优化哪一部分？</p><div class="mini-actions"><button type="button" data-answer="消息阅读" ${writeDisabled()}>消息阅读</button><button type="button" data-answer="输入与发送" ${writeDisabled()}>输入与发送</button></div>${conversationComposer('question')}`}else{body=form('mcp-form',`<label class="form-field">回应内容（JSON，可留空）<textarea name="content"></textarea></label>`,'允许并提交')+`<div class="mini-actions"><button data-decision="decline" ${writeDisabled()}>拒绝</button><button data-decision="cancel" ${writeDisabled()}>取消</button></div>`}
 return body}

function updateTimer(){const el=document.querySelector('#pair-timer');if(!el)return;const remaining=Math.max(0,Math.ceil((pairExpires-Date.now())/1000));el.textContent=pairCode?(remaining?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')} 后失效 · 演示码`:'配对码已过期，请重新生成'):'';const copy=document.querySelector('[data-feature="copy-pair"]');if(copy)copy.disabled=!pairCode||!remaining}
setInterval(updateTimer,1000);
function clearAttachments(){attachments.forEach(a=>URL.revokeObjectURL(a.url));attachments=[]}
function attachmentHTML(){return attachments.length?`<div class="attachment-list">${attachments.map((a,i)=>`<div class="attachment"><img src="${a.url}" alt="${esc(a.name)}"><button type="button" data-remove-image="${i}" aria-label="移除图片 ${i+1}">×</button></div>`).join('')}</div>`:''}
function filePicker(){if(!supportsComposerImages(document.querySelector('#message')?.closest('form')?.dataset.composer))return;const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.multiple=true;input.onchange=()=>{const files=[...input.files];if(files.length+attachments.length>3){toast('最多选择 3 张图片');return}if(files.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type))){toast('请选择 PNG、JPEG 或 WebP 图片');return}attachments.push(...files.map(f=>({name:f.name,url:URL.createObjectURL(f)})));document.querySelector('#attachments').innerHTML=attachmentHTML();updateComposer()};input.click()}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.answer){questionDraft=b.dataset.answer;document.querySelector('[name="answer"]').value=questionDraft;updateComposer();return}
 if(b.dataset.removeImage!==undefined){const i=Number(b.dataset.removeImage);URL.revokeObjectURL(attachments[i].url);attachments.splice(i,1);document.querySelector('#attachments').innerHTML=attachmentHTML();updateComposer();return}
 if(b.dataset.decision&&mode==='control'){requestType=b.closest('[data-request-kind]').dataset.requestKind;const kind=requestType,label=b.textContent.trim();confirmAction(label,'请核对请求内容和授权范围。本次仅演示，不执行实际审批。',()=>{answered.add(kind);syncRequests();record(label);render()});return}
 const a=b.dataset.feature;if(!a||a==='remove-device')return;
 if(a==='commit-confirm'){const run=confirmation;confirmation=null;sheet.close();run?.();return}
 if(a==='logout'){confirmAction('退出登录？','退出后返回登录页面。设备上的 Codex 任务会继续运行。',()=>{loggedIn=false;pairCode='';pairExpires=0;clearAttachments();Object.keys(drafts).forEach(k=>delete drafts[k]);location.hash='login';render()});return}
 if(a==='generate-pair'){pairCode='DEMO-'+String(Math.floor(1000+Math.random()*9000));pairExpires=Date.now()+300000;render();return}
 if(a==='copy-pair'){if(Date.now()>=pairExpires)return;try{await navigator.clipboard.writeText(pairCode);toast('已复制演示配对码')}catch{toast('复制不可用，请选择配对码手动复制')}return}

 if(a==='more'){if(!extraLoaded){sessions.push({id:5,project:'ConnectNow',title:'核对会话同步状态',preview:'更早的会话已加载',state:'done',time:'前天'});extraLoaded=true;render()}else toast('全部会话已加载');return}
 if(a==='compact'){if(mode==='control'&&sessions.find(s=>s.id===current).state==='done')confirmAction('压缩上下文？','仅压缩当前会话的上下文。',()=>{record('压缩上下文');location.hash='chat/'+current;render()});return}
 if(a==='attach'){if(mode==='control')filePicker();return}
 showFeature(a)
});
document.addEventListener('input',e=>{if(e.target.name==='answer'){questionDraft=e.target.value;updateComposer()}});
document.addEventListener('change',e=>{if(e.target.id==='temporary-select')document.querySelector('#temporary-message').textContent=e.target.selectedIndex?'请核对设备、会话和请求的关联关系。':'可以先核对核心流程，再逐项检查操作边界。'});
document.addEventListener('submit',e=>{const f=e.target;if(f.id==='composer')return;e.preventDefault();const data=new FormData(f),error=f.querySelector('.form-error');
 if(f.id==='login-form'){if(data.get('token')!=='demo'){error.textContent='此原型仅接受 demo，请勿输入真实凭证。';return}f.reset();loggedIn=true;location.hash='tasks';render();return}
 if(mode!=='control')return;
 const rawText=String(data.get('prompt')||'').trim();const text=rawText+(['new-form','edit-form'].includes(f.id)&&attachments.length?' [附 '+attachments.length+' 张图片]':'');
 try{if(['new-form','edit-form'].includes(f.id)&&attachments.length)throw Error('当前操作仅支持文字，请移除图片后发送；草稿已保留。');if(['new-form','edit-form'].includes(f.id)&&!text)throw Error('请输入任务内容。');
 if(f.id==='new-form'){if(!controller)throw Error('请先设置可用的控制会话。');const id=Math.max(...sessions.map(s=>s.id))+1;sessions.unshift({id,project:'独立任务',title:text.slice(0,28),preview:text,state:'running',time:'刚刚'});messages[id]=[text];drafts.new='';clearAttachments();record('创建独立会话');current=id;location.hash='chat/'+id;return}
 if(f.id==='controller-form'){controller=String(data.get('controller')||'');record('保存控制会话');location.hash='new';return}
 if(f.id==='edit-form'){confirmAction('替换并重新执行？','最后一轮输入及其后续结果会被替换。',()=>{messages[current]=[text];drafts['edit:'+current]='';clearAttachments();sessions.find(s=>s.id===current).state='running';record('编辑最后一轮');location.hash='chat/'+current});return}
 if(f.id==='settings-form'){const advanced=String(data.get('advanced')),parsed=JSON.parse(advanced);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw Error('设置 JSON 必须是对象。');confirmAction('保存会话设置？','设置会影响后续任务。请核对模型、权限与工作目录。',()=>{sessionSettings.advanced=advanced;record('保存会话设置');location.hash='chat/'+current});return}
 if(f.id==='question-form'){const answer=String(data.get('answer')||'').trim();if(!answer)throw Error('请回答全部问题。');answered.add('question');syncRequests();record('提交回答',answer);render();return}
 if(f.id==='permission-form'||f.id==='mcp-form'){const raw=String(data.get(f.id==='permission-form'?'permissions':'content')||'');if(raw){const obj=JSON.parse(raw);if(!obj||typeof obj!=='object'||Array.isArray(obj))throw Error('回应 JSON 必须是对象。')}confirmAction(f.id==='permission-form'?'确认授予所选权限？':'确认提交回应？',f.id==='permission-form'?`期限：${data.get('scope')==='turn'?'仅本轮':'整个会话'}；${data.has('review')?'继续逐条审查':'不启用逐条审查'}。`:'仅作用于当前 MCP 请求。',()=>{answered.add(requestType);record('提交 '+requestType+' 回应');render()});return}
 }catch(err){if(error)error.textContent=err.message}
});


function composerDraftKey(){const kind=document.querySelector('#message')?.closest('form')?.dataset.composer;return kind==='new'?'new':kind==='edit'?'edit:'+current:current}
function conversationComposer(kind){const question=kind==='question',key=kind==='new'?'new':kind==='edit'?'edit:'+current:current,id=kind==='chat'?'composer':kind+'-form',placeholder=kind==='new'?'描述你希望完成的任务…':kind==='edit'?'修改这条指令…':question?'输入你的回答…':'回复 Codex…',value=question?questionDraft:(drafts[key]??(kind==='edit'?'重新整理这项任务的结果。':''));return `<form class="composer ${question?'inline-composer':''}" id="${id}" data-composer="${kind}">${question?'':`<div id="attachments">${attachmentHTML()}</div>`}<div class="input-shell">${question?'':`<button type="button" class="icon-button" data-feature="attach" aria-label="添加图片" ${supportsComposerImages(kind)?'':'disabled'} title="${supportsComposerImages(kind)?'添加图片':'当前操作仅支持文字'}">＋</button>`}<textarea id="${question?'question-message':'message'}" name="${question?'answer':'prompt'}" rows="1" aria-label="${placeholder.replace('…','')}" placeholder="${placeholder}" ${writeDisabled()}>${esc(value)}</textarea><div class="composer-actions">${question?'':`<button type="button" class="model-button" id="model-trigger" aria-label="模型与思考强度" aria-expanded="false" popovertarget="model-popover" ${writeDisabled()}>${icon('settings')}</button>`}<button class="send-touch" ${question?'':'id="send-action"'} aria-label="${question?'提交回答':kind==='new'?'创建会话':kind==='edit'?'替换并重新执行':'发送指令'}" ${writeDisabled()}><span class="send">${icon('up')}</span></button></div></div>${question?'':modelPopover()}<p class="form-error" role="alert"></p>${mode==='control'?'':`<p class="compose-note">${mode==='readonly'?'只读连接 · 请在电脑端允许远程控制':'设备离线 · 连接恢复后可继续'}</p>`}</form>`}
function updateComposer(){document.querySelectorAll('form[data-composer]').forEach(form=>{const kind=form.dataset.composer,button=form.querySelector('.send-touch'),hasText=Boolean(form.querySelector('textarea').value.trim()||(kind!=='question'&&attachments.length)),running=kind==='chat'&&sessions.find(s=>s.id===current).state==='running';button.setAttribute('aria-label',kind==='new'?'创建会话':kind==='edit'?'替换并重新执行':kind==='question'?'提交回答':running&&!hasText?'停止任务':running?'发送补充指令':'发送指令');const unsupported=kind!=='question'&&attachments.length&&!supportsComposerImages(kind);button.disabled=mode!=='control'||(kind==='new'&&!controller)||(!running&&!hasText)||Boolean(unsupported);const error=form.querySelector('.form-error');if(unsupported)error.textContent='当前操作仅支持文字，请移除图片后发送；草稿已保留。';else if(error.textContent.includes('草稿已保留'))error.textContent='';button.querySelector('.send').innerHTML=running&&!hasText?'<span class="stop-symbol"></span>':icon('up');const input=form.querySelector('textarea');input.style.height='auto';input.style.height=Math.min(input.scrollHeight,110)+'px'})}

function supportsComposerImages(kind){return mode==='control'&&kind==='chat'&&sessions.find(s=>s.id===current)?.state==='done'}
function modelPopover(){return `<div id="model-popover" popover class="model-popover"><label>模型<select disabled aria-label="当前模型"><option>${esc(sessionSettings.model||'会话默认')}</option></select></label><label>思考强度<select disabled aria-label="当前思考强度"><option>${esc(sessionSettings.effort||'会话默认')}</option></select></label><p class="caption">当前可用选项尚未同步，可在 Codex App 中调整。</p></div>`}

function inlineRequests(){return ['command','question'].filter(type=>!answered.has(type)).map(type=>`<section class="approval inline-request" data-request-kind="${type}"><h3>${type==='question'?'Codex 需要你的回答':'需要批准这次操作'}</h3>${requestBody(type)}</section>`).join('')}
function syncRequests(){resolved=['command','question'].every(type=>answered.has(type));if(resolved){const t=sessions.find(s=>s.id===2);t.state='running';t.preview='正在继续处理';queue=queue.filter(q=>q.session!==2)}}
function pendingQueueHTML(){const items=queue.filter(q=>q.session===current);return items.length?`<section class="queued-messages"><span>等待当前请求处理后继续 · ${items.length} 条</span>${items.map(q=>`<p>${esc(q.text)}</p>`).join('')}</section>`:''}
document.addEventListener('change',e=>{if(mode!=='control')return;if(e.target.id==='quick-model')sessionSettings.model=e.target.value;if(e.target.id==='quick-effort')sessionSettings.effort=e.target.value});
document.addEventListener('toggle',e=>{if(e.target.id==='model-popover'){const trigger=document.querySelector('#model-trigger');if(trigger){trigger.setAttribute('aria-expanded',String(e.newState==='open'));if(e.newState==='open'){const r=trigger.getBoundingClientRect(),popover=e.target;popover.style.left=Math.max(12,Math.min(innerWidth-popover.offsetWidth-12,r.right-popover.offsetWidth+40))+'px';popover.style.bottom=(innerHeight-r.top+12)+'px'}}}},true);
let pull=null;
document.addEventListener('touchstart',e=>{const surface=e.target.closest('.scroll');if(loggedIn&&(location.hash==='#tasks'||location.hash.startsWith('#project/')||!location.hash)&&surface&&surface.scrollTop===0&&e.touches.length===1)pull={surface,y:e.touches[0].clientY,distance:0};else pull=null},{passive:true});
document.addEventListener('touchmove',e=>{if(!pull||e.touches.length!==1)return;const delta=e.touches[0].clientY-pull.y;if(delta<=0){pull=null;return}pull.distance=Math.min(delta,110);const status=document.querySelector('#pull-status');if(status){status.hidden=false;status.textContent=delta>65?'松开刷新':'下拉刷新';status.style.height=Math.min(delta/2,45)+'px'}if(e.cancelable)e.preventDefault()},{passive:false});
function finishPull(cancel=false){if(!pull)return;const refresh=!cancel&&pull.distance>65;pull=null;const status=document.querySelector('#pull-status');if(!status)return;if(refresh){status.textContent='正在刷新…';setTimeout(()=>{if(status.isConnected){status.textContent='已更新';document.querySelector('#session-list').innerHTML=list();setTimeout(()=>{status.hidden=true;status.style.height=''},450)}},350)}else{status.hidden=true;status.style.height=''}}
document.addEventListener('touchend',()=>finishPull());document.addEventListener('touchcancel',()=>finishPull(true));


const workspaces=[{id:'macbook',name:'我的 MacBook',status:'online',control:true},{id:'studio',name:'Mac Studio',status:'offline',control:false},{id:'office',name:'办公室 Mac',status:'error',control:false}];
let workspaceId='macbook';
const connectionRequests=[{id:'connection-example',name:'新的 MacBook',verification:'DEMO 42',createdAt:Date.now(),expiresAt:Date.now()+300000,state:'pending'}];
const consoleAddress='https://console.example.com';
function pendingConnections(){return connectionRequests.filter(r=>r.state==='pending'&&r.expiresAt>Date.now())}
function activeWorkspace(){return workspaces.find(w=>w.id===workspaceId)||{id:'',name:'尚未连接工作区',status:'offline',control:false}}
function workspaceStatus(status=activeWorkspace().status){return {online:{text:'在线',color:'#258441'},offline:{text:'离线',color:'#929299'},error:{text:'状态异常',color:'#cf3831'}}[status]}
function showWorkspaceSwitcher(){sheet.innerHTML=`<div class="handle"></div><div class="sheet-top"><h2 id="sheet-title">切换工作区</h2><button class="icon-button" data-action="close" aria-label="关闭">${icon('close')}</button></div><div class="group">${workspaces.map(w=>`<button class="workspace-option" data-workspace="${w.id}" aria-pressed="${workspaceId===w.id}"><span class="app-icon">${icon('device')}</span><span class="workspace-option-text"><strong>${esc(w.name)}</strong><small><i class="dot" style="color:${workspaceStatus(w.status).color}"></i>${workspaceStatus(w.status).text} · ${w.control?'允许远程控制':'只读'}</small></span>${workspaceId===w.id?icon('check'):''}</button>`).join('')||'<p class="empty">尚未连接工作区</p>'}</div><button class="primary new-workspace-link" data-workspace-action="new">连接新工作区</button>`;if(!sheet.open)sheet.showModal()}
function renderWorkspaceBinding(){page('连接新工作区',`<label class="form-field">此云端地址<input id="workspace-link" readonly value="${consoleAddress}"></label><button class="primary" data-workspace-action="copy">复制云端地址</button><ol class="caption"><li>在需要连接的电脑上打开 ConnectNow。</li><li>填写此云端地址并发起连接申请。</li><li>在手机的连接申请中核对设备、时间和两端确认码，确认后自动绑定。</li></ol><div class="group">${featureRow('link','连接申请',pendingConnections().length+' 项待确认')}</div><p class="caption">同一台电脑可连接多个云端。每条绑定默认只读，是否允许控制由本机分别决定。关闭本机网页后，后台仍可继续绑定。</p><p class="caption">此地址为设计示例，实际地址以已登录云端为准。</p>`,'devices')}
function connectionRequestCards(){return connectionRequests.filter(r=>r.state==='pending').map(r=>`<section class="approval"><h3>${esc(r.name)}</h3><p>申请时间：${new Date(r.createdAt).toLocaleTimeString('zh-CN')}<br>请核对电脑上显示的确认码。</p><div class="code-display">${esc(r.verification)}</div><p class="caption" data-connection-expiry="${r.id}"></p><div class="approval-actions"><button class="primary" data-connection-decision="accept" data-connection-id="${r.id}">确认连接</button><button class="secondary" data-connection-decision="reject" data-connection-id="${r.id}">拒绝</button></div></section>`).join('')||'<div class="group empty">暂无连接申请</div>'}
function renderConnectionRequests(){page('连接申请',connectionRequestCards()+'<p class="caption">确认后自动登记设备，无需预先选择设备 ID。远程控制权限仍由本机决定。</p>','devices');updateConnectionExpiry()}
function updateConnectionExpiry(){document.querySelectorAll('[data-connection-expiry]').forEach(el=>{const r=connectionRequests.find(r=>r.id===el.dataset.connectionExpiry),left=Math.max(0,Math.ceil((r.expiresAt-Date.now())/1000));el.textContent=left?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')} 后过期`:'申请已过期，请在本机重新发起';el.closest('section').querySelectorAll('button').forEach(b=>b.disabled=!left)})}
setInterval(updateConnectionExpiry,1000);
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.workspace){workspaceId=b.dataset.workspace;mode=activeWorkspace().status==='online'?(activeWorkspace().control?'control':'readonly'):'offline';clearAttachments();sheet.close();location.hash='devices';render();return}const a=b.dataset.workspaceAction;if(a==='new'){sheet.close();location.hash='bind-workspace'}if(a==='copy'){try{await navigator.clipboard.writeText(consoleAddress);toast('已复制云端地址')}catch{document.querySelector('#workspace-link').select();toast('请复制已选中的地址')}}if(b.dataset.connectionDecision){const r=connectionRequests.find(r=>r.id===b.dataset.connectionId);if(!r||r.state!=='pending'||r.expiresAt<=Date.now())return;const accept=b.dataset.connectionDecision==='accept';confirmAction(accept?'确认连接此设备？':'拒绝连接申请？',`${r.name} · 确认码 ${r.verification}。请确认这是你发起的申请。`,()=>{if(r.expiresAt<=Date.now()||r.state!=='pending'){render();return}r.state=accept?'accepted':'rejected';if(accept){workspaces.push({id:r.id,name:r.name,status:'offline',control:false});record('连接已确认','等待本机后台领取凭证并连接；如 Codex 不可用，请在本机开启桥接。')}render();toast(accept?'已确认，等待本机连接':'已拒绝申请')})}if(b.dataset.feature==='remove-device'){const id=workspaceId,name=activeWorkspace().name;if(!id)return;confirmAction('移除此设备？',`将撤销 ${name} 在此云端的凭证并断开连接。已在途的操作可能已经执行，请在本机核对。其他云端绑定不受影响。`,()=>{const i=workspaces.findIndex(w=>w.id===id);if(i>=0)workspaces.splice(i,1);workspaceId=workspaces[0]?.id||'';mode=activeWorkspace().status==='online'?(activeWorkspace().control?'control':'readonly'):'offline';clearAttachments();location.hash='devices';render()})}});
