const paths={chat:'<path d="M20 11.5a8 8 0 0 1-8 8H5l-3 2v-10a9 9 0 0 1 18 0Z"/>',activity:'<path d="M4 10a8 8 0 1 1 2 8M4 4v6h6m2-4v6l4 2"/>',settings:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',device:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M1 20h22"/>',back:'<path d="m15 4-8 8 8 8"/>',search:'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',up:'<path d="M12 20V4m-6 6 6-6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',code:'<path d="m7 6-5 6 5 6m10-12 5 6-5 6m-3-15-4 18"/>'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${paths[name]}</svg>`;
const sessions=[{id:1,project:'ConnectNow',title:'让手机上的对话更顺手',preview:'正在调整消息布局与键盘交互',state:'running',time:'现在'},{id:2,project:'ConnectNow',title:'检查远端连接',preview:'有一项操作需要你的确认',state:'wait',time:'5 分钟'},{id:3,project:'MarkFix',title:'重新梳理项目首页',preview:'页面结构和交互细节已整理完成',state:'done',time:'14:08'},{id:4,project:'ConnectNow',title:'准备下一次发布',preview:'安装说明与验证清单已更新',state:'done',time:'昨天'}];
let projectFilter='all',chatOrigin='',query='',mode='control',current=1,resolved=false;const drafts={},messages={};const app=document.querySelector('#app'),sheet=document.querySelector('#sheet');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const connection=()=>workspaceStatus().text;
function nav(page){return `<nav class="bottom-nav" aria-label="主导航">${[['tasks','chat','会话'],['inbox','activity','动态'],['devices','settings','设置']].map(([id,i,t])=>`<button data-route="${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon(i)}${t}${id==='inbox'&&(actionableSessions().length+pendingConnections().length)?`<span class="badge">${actionableSessions().length+pendingConnections().length}</span>`:''}</button>`).join('')}</nav>`}
function toolbar(){return `<header class="toolbar"><button class="device-switch" data-action="devices">${icon('device')} ${esc(activeWorkspace().name)} <span style="font-size:12px">⌄</span></button><span class="device-switch"><i class="dot" style="color:${workspaceStatus().color}"></i>${connection()}</span></header>`}
function row(t){return `<button class="session" data-task="${t.id}"><span class="app-icon ${t.state==='running'?'live':t.state}">${icon(t.state==='wait'?'lock':t.state==='running'?'code':'chat')}</span><span class="session-body"><span class="session-meta"><span>${t.project}</span><span>${t.time}</span></span><strong class="session-title">${t.title}${sessionUnread(t.id)?'<i class="unread-dot" aria-label="有未读消息"></i>':''}</strong><span class="session-preview" style="display:block">${t.preview}</span>${t.state!=='done'?`<span class="session-state ${t.state}"><i class="dot"></i>${t.state==='running'?'进行中':t.state==='failed'?'执行失败':'等待确认'}</span>`:''}</span>${icon('chevron','chevron')}</button>`}
function projectRoute(name){return 'project/'+encodeURIComponent(name)}
function selectedProject(){const hash=location.hash.slice(1);if(!hash.startsWith('project/'))return null;try{return decodeURIComponent(hash.slice(8))}catch{return null}}
function projectGroups(){const map=new Map();sessions.forEach(t=>{const name=t.project||'独立会话';if(!map.has(name))map.set(name,[]);map.get(name).push(t)});return [...map].map(([name,items])=>({name,items,waiting:items.filter(t=>t.state==='wait'||t.state==='failed').length,running:items.filter(t=>t.state==='running').length,unread:items.filter(t=>sessionUnread(t.id)).length})).sort((a,b)=>Number(b.waiting>0)-Number(a.waiting>0)||Number(b.running>0)-Number(a.running>0))}
function projectList(){const groups=projectGroups().filter(g=>g.name.toLowerCase().includes(query.toLowerCase()));return groups.length?`<div class="group">${groups.map(g=>`<button class="project-row" data-project="${esc(g.name)}"><span class="project-folder">${icon('code')}</span><span class="project-body"><strong>${esc(g.name)}</strong><span class="project-count">${g.items.length} 个会话</span><span class="project-statuses">${g.waiting?`<span class="project-wait">${g.waiting} 待处理</span>`:''}${g.running?`<span class="project-running">${g.running} 进行中</span>`:''}${g.unread?`<span class="project-unread">${g.unread} 未读</span>`:''}${!g.waiting&&!g.running&&!g.unread?'<span>暂无进行中的任务</span>':''}</span></span>${icon('chevron','chevron')}</button>`).join('')}</div>`:'<div class="empty">没有找到相关项目</div>'}
function list(){const project=selectedProject();if(project===null)return projectList();const visible=sessions.filter(t=>(t.project||'独立会话')===project&&(t.title+t.preview).toLowerCase().includes(query.toLowerCase())&&(projectFilter==='all'||(projectFilter==='wait'?['wait','failed'].includes(t.state):t.state==='running')));if(!visible.length)return '<div class="empty">没有匹配的会话</div>';return [['待处理',t=>['wait','failed'].includes(t.state)],['进行中',t=>t.state==='running'],['最近',t=>t.state==='done']].map(([title,match])=>{const items=visible.filter(match);return items.length?`<div class="group-title">${title}<span>${items.length}</span></div><div class="group">${items.map(row).join('')}</div>`:''}).join('')}
function renderProject(name){const items=sessions.filter(t=>(t.project||'独立会话')===name),waiting=items.filter(t=>['wait','failed'].includes(t.state)).length,running=items.filter(t=>t.state==='running').length;app.innerHTML=`<header class="toolbar"><button class="icon-button" data-project-back aria-label="返回项目">${icon('back')}</button><strong class="project-nav-title">${esc(name)}</strong><button class="icon-button" data-feature="new" aria-label="新建会话" ${writeDisabled()}>＋</button></header><main class="scroll"><div class="search-row"><label class="search">${icon('search')}<input id="search" type="search" aria-label="搜索项目内会话" placeholder="搜索会话" value="${esc(query)}"></label></div><div class="project-filters">${[['all','全部',items.length],['wait','待处理',waiting],['running','进行中',running]].map(([v,l,c])=>`<button data-project-filter="${v}" aria-pressed="${projectFilter===v}" class="${projectFilter===v?'active':''}">${l} ${c}</button>`).join('')}</div><div id="pull-status" role="status" hidden></div><section id="session-list">${list()}</section></main>`+nav('tasks')}

function render(){let route=location.hash.slice(1)||'tasks';if(renderFeature(route))return;if(route.startsWith('project/')){renderProject(selectedProject()||'独立会话');return}if(route.startsWith('chat/')){current=Number(route.split('/')[1]);if(!sessions.some(t=>t.id===current)){location.hash='tasks';return}markSessionRead(current);chat();return}if(route==='devices'){settings();return}if(route==='inbox'){renderActivity();return}app.innerHTML=toolbar()+`<main class="scroll"><div class="search-row"><label class="search">${icon('search')}<input id="search" type="search" aria-label="搜索项目" placeholder="搜索项目" value="${esc(query)}"></label><button class="icon-button" data-feature="new" aria-label="新建会话" ${mode!=='control'?'disabled':''}>＋</button></div><div id="pull-status" role="status" hidden></div><section id="session-list" aria-label="项目列表">${list()}</section></main>`+nav('tasks')}
function chat(){const t=sessions.find(s=>s.id===current);app.innerHTML=`<header class="toolbar chat-header"><button class="icon-button" data-route="${chatOrigin||projectRoute(t.project||'独立会话')}" aria-label="返回会话">${icon('back')}</button><div class="chat-heading"><strong>${t.title}</strong><small>${t.project} · ${connection()}</small></div><button class="icon-button" data-action="info" aria-label="会话信息">${icon('more')}</button></header><main class="scroll chat-scroll"><div class="chat-time">今天 14:32</div><div class="bubble">${current===1?'重新设计手机端的会话体验，让它更简洁，也更容易使用。':current===2?'帮我检查一下远端连接是否正常。':t.title+'，完成后整理一下结果。'}</div><div class="agent"><span class="agent-mark">✳</span>Codex</div><div class="response"><p>${current===1?'我会围绕阅读和回复，重新整理这段体验。':current===2?'设备已在线。接下来执行一次状态检查，需要你确认。':'已经完成整理，相关内容可以查看。'}</p>${current===1?'<p>界面会更专注于内容：</p><ul><li>消息自然展开，执行细节按需查看</li><li>主要操作留在拇指容易触达的位置</li><li>需要确认时，再呈现完整上下文</li></ul>':''}<details class="tool"><summary>${icon(current===2?'lock':'check')}${current===2?'待执行 · 状态检查':'已查看 3 个相关文件'}</summary><pre>${current===2?'connectnow status':'example.html\nstyle.css\napp.js'}</pre></details></div>${current===2?inlineRequests():''}${t.state==='running'?'<div class="running-label"><span class="activity-line"></span>正在继续处理</div>':''}${pendingQueueHTML()}<div id="received-messages">${receivedHTML(current)}</div><div id="sent-messages">${(messages[current]||[]).map(m=>`<div class="bubble" style="margin-top:18px">${esc(m)}</div>`).join('')}</div></main>${conversationComposer('chat')}`;updateComposer()}
function setting(iconName,label,value){return `<div class="setting"><span class="app-icon">${icon(iconName)}</span><span class="label">${label}</span><span class="value">${value}</span></div>`}
function settings(){app.innerHTML=`<main class="scroll workspace-settings"><section class="group device-card"><div class="device-art" aria-hidden="true"></div><div class="workspace-card-title"><h2>${esc(activeWorkspace().name)}</h2><button class="icon-button workspace-switch" data-action="devices" aria-label="切换工作区"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8h15m-4-4 4 4-4 4M20 16H5m4-4-4 4 4 4"/></svg></button></div><p class="workspace-status"><i class="dot" style="color:${workspaceStatus().color}"></i>${workspaceStatus().text}</p></section><div class="group-title">账户与配对</div><div class="group">${featureRow('link','连接申请',pendingConnections().length+' 项待确认')}${featureRow('bind-workspace','连接新工作区','')}${featureRow('remove-device','移除此设备','')}</div><div class="group-title">连接</div><div class="group">${setting('activity','远程待机',activeWorkspace().status==='online'?'已开启':'状态未知')}${setting('lock','远程控制',mode==='control'?'已允许':'不可用')}</div><p class="caption">本机分别管理各云端的控制权限。当前云端可查看本机桥接中的全部会话。</p><div class="group-title">通知</div><div class="group">${featureRow('notifications','消息通知','')}</div><div class="group-title">关于</div><div class="group">${setting('chat','ConnectNow','')}</div><button class="logout-button" data-feature="logout">退出登录</button></main>`+nav('devices')}
function showSheet(type){const top=title=>`<div class="handle"></div><div class="sheet-top"><h2 id="sheet-title">${title}</h2><button class="icon-button" data-action="close" aria-label="关闭">${icon('close')}</button></div>`;if(type==='devices'){showWorkspaceSwitcher();return}else{sheet.innerHTML=top('会话信息')+`<p>${sessions.find(t=>t.id===current).title}</p><div class="group">${setting('device','我的 MacBook',connection())}${setting('lock','控制权限',mode==='control'?'已允许':'不可用')}</div><p>这是设计预览，尚未连接真实会话。</p>`}sheet.showModal()}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.route)location.hash=b.dataset.route;if(b.dataset.task){chatOrigin=location.hash.slice(1)||'tasks';location.hash='chat/'+b.dataset.task;}if(b.dataset.mode){mode=b.dataset.mode;render()}const a=b.dataset.action;if(a==='close')sheet.close();if(a==='info')showFeature('operations');if(a==='devices')showSheet(a);if(a==='open-settings'){sheet.close();location.hash='devices'}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;document.querySelector('#session-list').innerHTML=list()}if(e.target.id==='message'){drafts[composerDraftKey()]=e.target.value;updateComposer()}});
document.addEventListener('submit',e=>{if(e.target.id!=='composer')return;e.preventDefault();if(mode!=='control')return;if(attachments.length&&!supportsComposerImages('chat')){updateComposer();return}const t=sessions.find(s=>s.id===current),value=document.querySelector('#message').value.trim();if(!value&&!attachments.length){if(t.state==='running'){t.state='done';t.preview='任务已停止';record('停止任务');chat()}return}const message=value+(attachments.length?' [附 '+attachments.length+' 张图片]':'');(messages[current]??=[]).push(message);if(t.state==='wait'){queue.push({id:nextQueue++,session:current,text:message,paused:true});record('指令已排队')}else{record(t.state==='running'?'补充指令':'发送指令');t.state='running'}clearAttachments();drafts[current]='';chat();const area=document.querySelector('.chat-scroll');area.scrollTop=area.scrollHeight});
window.addEventListener('hashchange',()=>{if(sheet.open)sheet.close();render()});

document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.project!==undefined){query='';projectFilter='all';location.hash=projectRoute(b.dataset.project)}if(b.hasAttribute('data-project-back')){query='';projectFilter='all';location.hash='tasks'}if(b.dataset.projectFilter){projectFilter=b.dataset.projectFilter;render()}});
