// Local event fixtures for the notification design. No system notification permission or push subscription.
const noticeKinds={message:{title:'新消息',icon:'chat'},done:{title:'任务已完成',icon:'check'},failed:{title:'任务遇到问题',icon:'activity'},approval:{title:'需要你的确认',icon:'lock'}};
const notificationEvents=[{id:1,session:2,kind:'approval',text:'检查远端连接需要你的批准与回答。',read:false,time:Date.now()}];
const received={};let eventSequence=2;
const noticePreferences={message:true,done:true,failed:true,approval:true};
function unreadCount(){return notificationEvents.filter(n=>!n.read).length}
function sessionUnread(id){return notificationEvents.some(n=>n.session===id&&!n.read)}
function markSessionRead(id){notificationEvents.filter(n=>n.session===id).forEach(n=>n.read=true)}
function receivedHTML(id){return (received[id]||[]).map(n=>`<div class="agent"><span class="agent-mark">✳</span>Codex</div><div class="response received-message"><p>${esc(n.text)}</p></div>`).join('')}
function refreshBadges(){const nav=document.querySelector('.bottom-nav');if(nav)nav.outerHTML=windowNav();const listArea=document.querySelector('#session-list');if(listArea)listArea.innerHTML=list();const project=selectedProject();if(project!==null){const items=sessions.filter(t=>(t.project||'独立会话')===project);document.querySelectorAll('[data-project-filter]').forEach(b=>{const v=b.dataset.projectFilter;b.textContent=v==='all'?'全部 '+items.length:v==='wait'?'待处理 '+items.filter(t=>['wait','failed'].includes(t.state)).length:'进行中 '+items.filter(t=>t.state==='running').length})}}
function windowNav(){return nav(location.hash.startsWith('#project/')?'tasks':location.hash.slice(1)||'tasks')}
function eventTime(time){return Date.now()-time<60000?'刚刚':new Date(time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}
function activityRow(n){const t=sessions.find(t=>t.id===n.session),kind=noticeKinds[n.kind];return `<button class="activity-event" data-notification="${n.id}"><span class="app-icon ${n.kind==='failed'?'notice-failed':n.kind==='approval'?'wait':''}">${icon(kind.icon)}</span><span class="activity-content"><span class="session-meta"><span>${kind.title}</span><span>${eventTime(n.time)}</span></span><strong>${esc(t?.title||'会话')}</strong><p>${esc(n.text)}</p></span>${!n.read?'<i class="unread-dot" aria-label="未读"></i>':icon('chevron','chevron')}</button>`}
function actionableSessions(){return workspaceId==='macbook'?sessions.filter(t=>['wait','failed'].includes(t.state)):[]}
function renderActivity(){const items=actionableSessions();app.innerHTML=toolbar()+`<main class="scroll">${pendingConnections().length?`<div class="group-title">连接申请<span>${pendingConnections().length} 项</span></div><div class="group">${featureRow('link','有新的电脑申请连接',pendingConnections().length+' 项待确认')}</div>`:''}<div class="group-title">需要处理<span>${items.length} 个会话</span></div>${items.length?`<div class="group">${items.map(row).join('')}</div>`:'<div class="group empty">暂时没有需要处理的会话</div>'}<p class="caption">待确认、待回答与执行失败的会话集中显示在这里。</p></main>`+nav('inbox')}

function renderNotifications(){page('消息通知',`<div class="group-title">接收通知</div><div class="group">${Object.entries(noticeKinds).map(([key,k])=>switchRow(key,k.title)).join('')}</div><p class="caption">选择需要提醒的事件。关闭提醒后，仍可在动态中查看记录。</p><div class="group-title">通知方式</div><div class="group">${setting('lock','横幅、声音与锁屏','系统管理')}</div><p class="caption">在手机系统设置中管理 ConnectNow 的通知权限与显示方式。</p>`) }

function switchRow(key,label){return `<label class="setting notice-switch"><span class="label">${label}</span><input type="checkbox" role="switch" data-notice-pref="${key}" ${noticePreferences[key]?'checked':''}><span class="switch-track" aria-hidden="true"></span></label>`}
function receiveNotification(kind){if(!loggedIn)return;const id=kind==='approval'?2:kind==='failed'?4:1;const text={message:'已完成页面结构检查，正在整理下一步调整。',done:'调整已完成，验证结果已整理，可以查看。',failed:'检查未能完成，需要查看错误详情后继续。',approval:'有新的操作等待确认，请核对后处理。'}[kind];const active=document.visibilityState==='visible'&&location.hash==='#chat/'+id;const n={id:eventSequence++,session:id,kind,text,read:active,time:Date.now()};notificationEvents.unshift(n);const t=sessions.find(t=>t.id===id);t.preview=text;t.time='刚刚';if(kind==='done')t.state='done';if(kind==='failed')t.state='failed';if(kind==='approval'){t.state='wait';answered.clear();resolved=false}(received[id]??=[]).push(n);
 if(active){const area=document.querySelector('.chat-scroll'),atBottom=area.scrollHeight-area.scrollTop-area.clientHeight<80,oldScroll=area.scrollTop;if(kind==='approval'){chat();document.querySelector('.chat-scroll').scrollTop=oldScroll}else{document.querySelector('#received-messages').innerHTML=receivedHTML(id);updateComposer()}if(atBottom)document.querySelector('.chat-scroll').scrollTop=document.querySelector('.chat-scroll').scrollHeight}
 else if(location.hash==='#inbox')renderActivity();else refreshBadges();
 const announcer=document.querySelector('#notice-announcer');announcer.textContent=noticeKinds[kind].title+'：'+text;
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.notification){const n=notificationEvents.find(n=>n.id===Number(b.dataset.notification));if(!n)return;chatOrigin='inbox';markSessionRead(n.session);if(sheet.open)sheet.close();location.hash='chat/'+n.session;render();return}if(b.dataset.noticeAction==='read-all'){notificationEvents.forEach(n=>n.read=true);renderActivity()}});
document.addEventListener('change',e=>{if(e.target.dataset.noticePref)noticePreferences[e.target.dataset.noticePref]=e.target.checked});
const announcer=document.createElement('div');announcer.id='notice-announcer';announcer.className='sr-only';announcer.setAttribute('role','status');announcer.setAttribute('aria-live','polite');document.body.append(announcer);
render();
